{"name": "test_xfail", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <tests.test_marks.TestMarks object at 0x104824750>\n\n    @pytest.mark.xfail\n    def test_xfail(self):\n        \"\"\"\n        Indicate that you expect it to fail\n        这条用例执行失败时，测试结果被标记为xfail(expected to fail)，并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed(unexpectedly passing)\n        :return:\n        \"\"\"\n>       assert 0\nE       assert 0\n\ntests/test_marks.py:40: AssertionError"}, "description": "\n        Indicate that you expect it to fail\n        这条用例执行失败时，测试结果被标记为xfail(expected to fail)，并且不打印错误信息。\n        这条用例执行成功时，测试结果被标记为xpassed(unexpectedly passing)\n        :return:\n        ", "start": 1591176793940, "stop": 1591176793940, "uuid": "58617fd8-dbe9-4a9b-947e-d438b906a11c", "historyId": "a44cab49732a0aa43a757be1adf99317", "testCaseId": "bddf35a14fb9223139b80ad1c562cbae", "fullName": "tests.test_marks.TestMarks#test_xfail", "labels": [{"name": "tag", "value": "xfail"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_marks"}, {"name": "subSuite", "value": "TestMarks"}, {"name": "host", "value": "LIUMENGJIAdeMacBook-Pro.local"}, {"name": "thread", "value": "78122-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_marks"}]}