{"name": "test_func", "status": "failed", "statusDetails": {"message": "AssertionError: assert [1, 2, 3] == [1, 2, 4]\n  At index 2 diff: 3 != 4\n  Use -v to get the full diff", "trace": "def test_func():\n        def func():\n            return [1,2,3]\n    \n>       assert func() == [1,2,4]\nE       assert [1, 2, 3] == [1, 2, 4]\nE         At index 2 diff: 3 != 4\nE         Use -v to get the full diff\n\ntests/test_assertions.py:33: AssertionError"}, "start": 1591176793757, "stop": 1591176793757, "uuid": "cb94e919-0391-44d4-90d7-c4636589636c", "historyId": "c7deb80c02a641c44581a601d8aa78ec", "testCaseId": "ab2a61770e0e2adc57d2cc47c52ef550", "fullName": "tests.test_assertions#test_func", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_assertions"}, {"name": "host", "value": "LIUMENGJIAdeMacBook-Pro.local"}, {"name": "thread", "value": "78122-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_assertions"}]}